
trailingComma: 'es5'
tabWidth: 2
semi: true
singleQuote: true
arrowParens: always
bracketSpacing: true
jsxSingleQuote: false
jsxBracketSameLine: false
quoteProps: consistent
printWidth: 120
proseWrap: always
